const questions = [
    ["What is the brain of a computer?", "RAM", "CPU", "Hard Disk", "Monitor", 2],
    ["What is the full form of RAM?", "Read Access Memory", "Random Access Memory", "Run Access Memory", "Rapid Access Memory", 2],
    ["How many bits are there in 1 Byte?", "4", "8", "16", "32", 2],
    ["What is the smallest unit of data in a computer?", "Byte", "Bit", "Nibble", "Word", 2],
    ["How many bits are there in 1 Nibble?", "2", "4", "8", "16", 2],
    ["What is the full form of ROM?", "Random Only Memory", "Read Only Memory", "Read Open Memory", "Run Only Memory", 2],
    ["Which memory is volatile?", "ROM", "RAM", "CD-ROM", "Hard Disk", 2],
    ["What is the full form of ALU?", "Arithmetic Logic Unit", "Arithmetic Local Unit", "Advanced Logic Unit", "Application Logic Unit", 1],
    ["Which of the following is an operating system?", "Windows", "MS Word", "Google Chrome", "Photoshop", 1],
    ["Which digits are used in the binary number system?", "0 and 1", "1 and 2", "0 to 7", "0 to 9", 1],
    ["What is the base of the decimal number system?", "2", "8", "10", "16", 3],
    ["What is the decimal value of binary 1010?", "8", "10", "12", "14", 2],
    ["What is the base of the hexadecimal number system?", "2", "8", "10", "16", 4],
    ["What is the main function of a compiler?", "Repair hardware", "Translate source code into machine/object code", "Connect to the Internet", "Delete files", 2],
    ["Who developed the C programming language?", "James Gosling", "Dennis Ritchie", "Bjarne Stroustrup", "Guido van Rossum", 2],
    ["C++ is an extension of which language?", "Java", "C", "Python", "BASIC", 2],
    ["Who developed C++?", "Dennis Ritchie", "Bjarne Stroustrup", "James Gosling", "Ken Thompson", 2],
    ["What is the full form of OOP?", "Object Oriented Programming", "Object Operating Program", "Online Object Programming", "Oriented Operating Programming", 1],
    ["Which is a fundamental concept of OOP?", "Encapsulation", "Compilation", "Formatting", "Debugging", 1],
    ["Which OOP concept binds data and methods together?", "Inheritance", "Encapsulation", "Polymorphism", "Compilation", 2],
    ["What is the full form of SQL?", "Structured Query Language", "Simple Query Language", "Standard Question Language", "System Query Logic", 1],
    ["Which SQL command is used to retrieve data?", "INSERT", "UPDATE", "SELECT", "DELETE", 3],
    ["Which SQL command is used to delete records?", "REMOVE", "DELETE", "CLEAR", "ERASE", 2],
    ["What is the main purpose of a Primary Key?", "Create duplicate records", "Uniquely identify records", "Delete a table", "Shut down a database", 2],
    ["What is the full form of DBMS?", "Database Management System", "Data Backup Management System", "Database Machine System", "Data Management Software", 1],
    ["A process waiting for an event is generally in which state?", "Ready", "Waiting/Blocked", "Running", "Terminated", 2],
    ["Which is a CPU scheduling algorithm?", "FCFS", "FTP", "HTTP", "DNS", 1],
    ["What is the full form of LAN?", "Large Area Network", "Local Area Network", "Logical Area Network", "Long Area Network", 2],
    ["Which protocol is commonly used to transfer web pages?", "HTTP", "FTP", "SMTP", "POP3", 1],
    ["What is the full form of IP?", "Internet Protocol", "Internal Program", "Internet Program", "Information Protocol", 1],
    ["Which device is used to enter data into a computer?", "Monitor", "Keyboard", "Printer", "Speaker", 2],
    ["Which of the following is an output device?", "Mouse", "Keyboard", "Monitor", "Scanner", 3],
    ["Which of the following is secondary storage?", "RAM", "Register", "Cache", "Hard Disk", 4],
    ["Which memory is the fastest?", "Hard Disk", "RAM", "Cache", "Register", 4],
    ["What is the full form of CPU?", "Central Processing Unit", "Computer Processing Unit", "Central Program Unit", "Control Processing Unit", 1],
    ["Which part of the CPU performs arithmetic operations?", "CU", "ALU", "RAM", "ROM", 2],
    ["Which unit controls all operations of a computer?", "ALU", "Control Unit", "RAM", "Hard Disk", 2],
    ["What is the binary equivalent of decimal 15?", "1110", "1111", "1011", "1101", 2],
    ["What is the decimal equivalent of binary 1101?", "11", "12", "13", "14", 3],
    ["What is the octal equivalent of decimal 8?", "8", "10", "11", "100", 2],
    ["Which symbol is used to end a statement in C?", ":", ";", ".", ",", 2],
    ["Which function is the entry point of a C program?", "start()", "begin()", "main()", "init()", 3],
    ["Which header file is required for printf() and scanf() in C?", "math.h", "string.h", "stdio.h", "stdlib.h", 3],
    ["Which symbol is used for a single-line comment in C++?", "/* */", "//", "#", "<!-- -->", 2],
    ["Which data type is used to store an integer in C?", "float", "char", "int", "double", 3],
    ["Which data type is used to store a single character?", "int", "char", "string", "float", 2],
    ["Which operator is used for assignment?", "==", "=", "!=", ">=", 2],
    ["Which operator compares two values for equality?", "=", "==", "!=", ":=", 2],
    ["Which loop executes at least once?", "for loop", "while loop", "do-while loop", "None", 3],
    ["Which keyword is used to exit a loop immediately?", "stop", "exit", "break", "continue", 3],
    ["Which keyword skips the current iteration of a loop?", "break", "continue", "skip", "return", 2],
    ["Which operator is known as the modulus operator?", "/", "*", "%", "//", 3],
    ["What is the output of 5 % 2?", "0", "1", "2", "2.5", 2],
    ["Which keyword is used to define a constant in C++?", "fixed", "final", "const", "static", 3],
    ["Which keyword is used to dynamically allocate memory in C++?", "malloc", "new", "alloc", "create", 2],
    ["Which keyword is used to release dynamically allocated memory in C++?", "remove", "free", "delete", "clear", 3],
    ["What is a function that calls itself called?", "Recursive function", "Nested function", "Inline function", "Virtual function", 1],
    ["Which concept allows multiple functions with the same name but different parameters?", "Inheritance", "Function Overloading", "Encapsulation", "Recursion", 2],
    ["Which OOP feature allows a class to inherit properties from another class?", "Polymorphism", "Abstraction", "Inheritance", "Encapsulation", 3],
    ["Which OOP concept means one interface with many forms?", "Encapsulation", "Inheritance", "Polymorphism", "Abstraction", 3],
    ["Which data structure follows FIFO?", "Stack", "Queue", "Tree", "Graph", 2],
    ["Which data structure follows LIFO?", "Queue", "Array", "Stack", "Linked List", 3],
    ["What is the operation of inserting an element into a stack called?", "Pop", "Push", "Insert", "Add", 2],
    ["What is the operation of removing an element from a stack called?", "Push", "Delete", "Pop", "Remove", 3],
    ["Which data structure is used in recursion?", "Queue", "Stack", "Array", "Tree", 2],
    ["Which data structure stores elements in contiguous memory locations?", "Linked List", "Tree", "Array", "Graph", 3],
    ["In a linked list, each element is called a:", "Node", "Vertex", "Index", "Edge", 1],
    ["Which data structure is suitable for implementing a printer queue?", "Stack", "Queue", "Tree", "Graph", 2],
    ["What is the top element of a stack called?", "Front", "Rear", "Top", "Root", 3],
    ["In a binary tree, a node can have at most how many children?", "1", "2", "3", "Unlimited", 2],
    ["Which SQL command is used to add new records?", "ADD", "INSERT", "CREATE", "UPDATE", 2],
    ["Which SQL command is used to modify existing records?", "MODIFY", "CHANGE", "UPDATE", "ALTER", 3],
    ["Which SQL command is used to create a table?", "MAKE TABLE", "NEW TABLE", "CREATE TABLE", "BUILD TABLE", 3],
    ["Which SQL command is used to remove an entire table?", "DELETE TABLE", "DROP TABLE", "REMOVE TABLE", "CLEAR TABLE", 2],
    ["Which key establishes a relationship between two tables?", "Primary Key", "Foreign Key", "Candidate Key", "Alternate Key", 2],
    ["Which SQL clause is used to filter records?", "WHERE", "ORDER BY", "GROUP BY", "HAVING", 1],
    ["Which SQL clause is used to sort query results?", "SORT BY", "ORDER BY", "GROUP BY", "ARRANGE BY", 2],
    ["Which SQL function is used to count rows?", "SUM()", "COUNT()", "TOTAL()", "NUMBER()", 2],
    ["Which normal form removes partial dependency?", "1NF", "2NF", "3NF", "BCNF", 2],
    ["Which normal form removes transitive dependency?", "1NF", "2NF", "3NF", "4NF", 3],
    ["Which of the following is an operating system?", "Linux", "Oracle", "MySQL", "Python", 1],
    ["What is multitasking?", "Running only one program", "Running multiple programs simultaneously", "Deleting multiple files", "Using multiple computers", 2],
    ["What is deadlock?", "A process completes successfully", "Processes wait indefinitely for resources", "The computer is turned off", "Memory is deleted", 2],
    ["Which scheduling algorithm selects the process with the shortest burst time?", "FCFS", "Round Robin", "SJF", "Priority Scheduling", 3],
    ["Which scheduling algorithm uses a time quantum?", "FCFS", "SJF", "Round Robin", "Priority", 3],
    ["What is the full form of WAN?", "Wide Area Network", "Wireless Area Network", "Web Area Network", "World Area Network", 1],
    ["Which device connects different networks?", "Hub", "Switch", "Router", "Repeater", 3],
    ["Which device forwards data based on MAC addresses?", "Router", "Switch", "Modem", "Gateway", 2],
    ["What is the full form of URL?", "Uniform Resource Locator", "Universal Resource Link", "Uniform Reference Link", "Universal Reference Locator", 1],
    ["Which protocol is used to send email?", "HTTP", "FTP", "SMTP", "POP3", 3],
    ["Which protocol is commonly used to receive emails?", "SMTP", "POP3", "HTTP", "FTP", 2],
    ["What does DNS do?", "Transfers files", "Converts domain names into IP addresses", "Sends emails", "Encrypts files", 2],
    ["Which network topology uses a central hub or switch?", "Bus", "Ring", "Star", "Mesh", 3],
    ["Which topology connects devices in a closed loop?", "Star", "Bus", "Ring", "Tree", 3],
    ["Which OSI layer is responsible for routing?", "Physical Layer", "Data Link Layer", "Network Layer", "Transport Layer", 3],
    ["Which protocol provides reliable, connection-oriented communication?", "UDP", "TCP", "IP", "HTTP", 2],
    ["Which protocol is connectionless?", "TCP", "UDP", "FTP", "SMTP", 2],
    ["What is the full form of HTML?", "Hyper Text Markup Language", "High Text Machine Language", "Hyper Transfer Markup Language", "Home Tool Markup Language", 1],
    ["Which HTML tag is used to create a hyperlink?", "<link>", "<a>", "<href>", "<url>", 2],
    ["Which HTML tag is used to insert an image?", "<image>", "<picture>", "<img>", "<src>", 3],
    ["Which HTML tag is used to insert an image?", "<image>", "<picture>", "<img>", "<src>", 3],
    ["Which language is used to style HTML pages?", "Python", "CSS", "SQL", "C++", 2],
    ["What is the full form of CSS?", "Computer Style Sheets", "Cascading Style Sheets", "Creative Style System", "Colorful Style Sheets", 2],
    ["Which HTML tag is used to create a paragraph?", "<para>", "<p>", "<paragraph>", "<text>", 2],
    ["Which HTML tag creates the largest heading?", "<h6>", "<heading>", "<h1>", "<head>", 3],
    ["Which CSS property changes text color?", "font-color", "text-color", "color", "foreground", 3],
    ["Which CSS property changes the background color?", "bgcolor", "background-color", "color-background", "background", 2],
    ["Which keyword declares a variable in JavaScript?", "var", "variable", "declare", "letvar", 1],
    ["Which symbol is used for comments in JavaScript single-line comments?", "//", "/*", "#", "<!--", 1],
    ["Which language is mainly used to make web pages interactive?", "HTML", "CSS", "JavaScript", "SQL", 3],
    ["What is the full form of WWW?", "World Wide Web", "World Web Window", "Wide World Web", "Web World Wide", 1],
    ["Who invented the World Wide Web?", "Bill Gates", "Tim Berners-Lee", "Steve Jobs", "Mark Zuckerberg", 2],
    ["Which protocol is used for secure web communication?", "HTTP", "HTTPS", "FTP", "SMTP", 2],
    ["What does HTTPS provide?", "Compression only", "Security through encryption", "Faster CPU", "File deletion", 2],
    ["Which port is commonly associated with HTTP?", "21", "25", "80", "443", 3],
    ["Which port is commonly associated with HTTPS?", "80", "110", "443", "8080", 3],
    ["What is the full form of FTP?", "File Transfer Protocol", "Fast Transfer Program", "File Transmission Program", "Folder Transfer Protocol", 1],
    ["Which protocol is used for remote login?", "Telnet", "SMTP", "HTTP", "POP3", 1],
    ["What is an IP address used for?", "Identifying a device on a network", "Formatting a disk", "Running programs", "Printing documents", 1],
    ["How many bits are there in an IPv4 address?", "16", "32", "64", "128", 2],
    ["How many bits are there in an IPv6 address?", "32", "64", "128", "256", 3],
    ["Which device connects computers within a LAN?", "Switch", "Printer", "Scanner", "CPU", 1],
    ["Which device regenerates weak signals?", "Router", "Repeater", "Switch", "Bridge", 2],
    ["Which device converts digital signals to analog signals?", "Modem", "Switch", "Hub", "Router", 1],
    ["What is the full form of MAC?", "Media Access Control", "Machine Access Control", "Media Application Control", "Memory Access Code", 1],
    ["A MAC address is usually how many bits long?", "32", "48", "64", "128", 2],
    ["Which protocol automatically assigns IP addresses?", "DNS", "DHCP", "FTP", "SMTP", 2],
    ["What is the full form of DHCP?", "Dynamic Host Configuration Protocol", "Data Host Control Protocol", "Dynamic Hardware Control Protocol", "Digital Host Configuration Program", 1],
    ["What is the full form of DNS?", "Domain Name System", "Data Name System", "Domain Network Service", "Digital Name Service", 1],
    ["Which layer of OSI model deals with physical transmission of bits?", "Physical Layer", "Network Layer", "Transport Layer", "Session Layer", 1],
    ["How many layers are there in the OSI model?", "5", "6", "7", "8", 3],
    ["Which OSI layer provides end-to-end delivery?", "Network", "Transport", "Session", "Data Link", 2],
    ["Which OSI layer is responsible for logical addressing?", "Physical", "Data Link", "Network", "Presentation", 3],
    ["Which OSI layer uses MAC addresses?", "Physical", "Data Link", "Network", "Transport", 2],
    ["Which OSI layer is responsible for encryption and compression?", "Session", "Presentation", "Network", "Physical", 2],
    ["Which OSI layer establishes and manages sessions?", "Session", "Transport", "Network", "Data Link", 1],
    ["Which protocol is used to transfer files securely?", "SFTP", "HTTP", "SMTP", "POP3", 1],
    ["Which protocol is used to resolve IP addresses to MAC addresses?", "ARP", "DNS", "FTP", "DHCP", 1],
    ["What is the full form of ARP?", "Address Resolution Protocol", "Address Routing Protocol", "Automatic Resolution Program", "Advanced Routing Protocol", 1],
    ["Which protocol is used to test network connectivity?", "ICMP", "SMTP", "FTP", "POP3", 1],
    ["Which command is commonly used to test connectivity?", "ping", "copy", "format", "mkdir", 1],
    ["Which topology has a single central connection point?", "Bus", "Ring", "Star", "Mesh", 3],
    ["Which topology provides the highest redundancy?", "Bus", "Star", "Mesh", "Ring", 3],
    ["Which topology uses a single backbone cable?", "Star", "Bus", "Mesh", "Ring", 2],
    ["Which network covers a small geographical area?", "LAN", "WAN", "MAN", "GAN", 1],
    ["Which network covers a metropolitan area?", "LAN", "MAN", "WAN", "PAN", 2],
    ["Which network covers a large geographical area?", "PAN", "LAN", "WAN", "CAN", 3],
    ["What is the full form of PAN?", "Personal Area Network", "Private Area Network", "Public Area Network", "Personal Access Network", 1],
    ["Bluetooth is commonly used for which type of network?", "PAN", "WAN", "MAN", "GAN", 1],
    ["Which technology is commonly used for wireless LAN?", "Wi-Fi", "FTP", "SMTP", "DNS", 1],
    ["Which device broadcasts data to all connected ports?", "Switch", "Hub", "Router", "Bridge", 2],
    ["Which data structure is based on FIFO?", "Stack", "Queue", "Tree", "Graph", 2],
    ["Which data structure is based on LIFO?", "Queue", "Stack", "Array", "Graph", 2],
    ["What is insertion into a stack called?", "Push", "Pop", "Peek", "Delete", 1],
    ["What is deletion from a stack called?", "Push", "Insert", "Pop", "Peek", 3],
    ["Which operation returns the top stack element without removing it?", "Push", "Pop", "Peek", "Delete", 3],
    ["Which data structure is commonly used for BFS?", "Stack", "Queue", "Heap", "Array", 2],
    ["Which data structure is commonly used for DFS?", "Queue", "Stack", "Hash Table", "Array", 2],
    ["What is the worst-case time complexity of linear search?", "O(1)", "O(log n)", "O(n)", "O(n²)", 3],
    ["What is the average time complexity of binary search?", "O(n)", "O(log n)", "O(n²)", "O(1)", 2],
    ["Binary search requires the data to be:", "Random", "Sorted", "Encrypted", "Duplicated", 2],
    ["What is the worst-case time complexity of bubble sort?", "O(n)", "O(log n)", "O(n²)", "O(1)", 3],
    ["Which sorting algorithm repeatedly selects the minimum element?", "Bubble Sort", "Selection Sort", "Merge Sort", "Quick Sort", 2],
    ["Which sorting algorithm uses divide and conquer?", "Merge Sort", "Bubble Sort", "Selection Sort", "Linear Sort", 1],
    ["What is the average time complexity of Merge Sort?", "O(n)", "O(n log n)", "O(n²)", "O(log n)", 2],
    ["What is the average time complexity of Quick Sort?", "O(n)", "O(log n)", "O(n log n)", "O(n²)", 3],
    ["What is the worst-case complexity of Quick Sort?", "O(n)", "O(n log n)", "O(n²)", "O(log n)", 3],
    ["Which data structure uses nodes and pointers?", "Array", "Linked List", "Stack only", "Queue only", 2],
    ["What does the first node of a linked list represent?", "Tail", "Head", "Root", "Top", 2],
    ["What does the last node of a linked list usually contain?", "Previous pointer", "Null pointer", "Root", "Stack pointer", 2],
    ["Which linked list allows traversal in both directions?", "Singly Linked List", "Doubly Linked List", "Circular Queue", "Stack", 2],
    ["Which data structure is hierarchical?", "Array", "Tree", "Stack", "Queue", 2],
    ["The top node of a tree is called:", "Leaf", "Root", "Edge", "Child", 2],
    ["A node with no children is called:", "Root", "Parent", "Leaf", "Sibling", 3],
    ["How many children can a binary tree node have at most?", "1", "2", "3", "4", 2],
    ["Which traversal visits Root, Left, Right?", "Inorder", "Postorder", "Preorder", "Level Order", 3],
    ["Which traversal visits Left, Root, Right?", "Preorder", "Inorder", "Postorder", "Level Order", 2],
    ["Which traversal visits Left, Right, Root?", "Preorder", "Inorder", "Postorder", "Level Order", 3],
    ["A graph consists mainly of:", "Nodes and arrays", "Vertices and edges", "Stacks and queues", "Keys and values", 2],
    ["Another name for a vertex in a graph is:", "Node", "Pointer", "Index", "Root", 1],
    ["Which algorithm finds the shortest path from a source in a weighted graph with non-negative weights?", "Dijkstra's Algorithm", "DFS", "BFS", "Binary Search", 1],
    ["Which data structure is commonly used to implement a priority queue?", "Heap", "Stack", "Linked List only", "Graph", 1],
    ["What is the root element of a max heap?", "Minimum", "Maximum", "Average", "Random", 2],
    ["What is the root element of a min heap?", "Maximum", "Minimum", "Median", "Random", 2],
    ["Which data structure provides average O(1) search using hashing?", "Hash Table", "Stack", "Queue", "Tree", 1],
    ["A hash function maps a key to a:", "Memory address/index", "CPU register", "File", "Process", 1],
    ["What is a collision in hashing?", "Two keys map to the same location", "A program crash", "Memory deletion", "CPU failure", 1],
    ["Which technique can resolve hash collisions?", "Chaining", "Compilation", "Paging", "Fragmentation", 1],
    ["Which tree is a self-balancing binary search tree?", "AVL Tree", "Binary Heap", "B-Tree only", "Trie", 1],
    ["What is the balance factor of an AVL tree node allowed to be?", "-1, 0, or +1", "Only 0", "Only +1", "Any value", 1],
    ["What is the main property of a Binary Search Tree?", "Left < Root < Right", "Left > Root > Right", "All nodes equal", "No ordering", 1],
    ["What does DBMS stand for?", "Database Management System", "Data Backup Management System", "Database Machine System", "Data Management Software", 1],
    ["Which language is used to query relational databases?", "SQL", "HTML", "CSS", "XML", 1],
    ["Which SQL command retrieves records?", "SELECT", "INSERT", "UPDATE", "DELETE", 1],
    ["Which SQL command adds records?", "SELECT", "INSERT", "UPDATE", "DROP", 2],
    ["Which SQL command modifies records?", "UPDATE", "INSERT", "DELETE", "CREATE", 1],
    ["Which SQL command removes records?", "DELETE", "DROP", "REMOVE", "CLEAR", 1],
    ["Which SQL command creates a database object?", "CREATE", "SELECT", "READ", "FETCH", 1],
    ["Which SQL command removes a table completely?", "DELETE", "DROP", "REMOVE", "CLEAR", 2],
    ["Which clause filters rows in SQL?", "WHERE", "ORDER BY", "GROUP BY", "SELECT", 1],
    ["Which clause sorts SQL query results?", "SORT BY", "ORDER BY", "GROUP BY", "ARRANGE BY", 2],
    ["Which SQL clause groups rows?", "GROUP BY", "ORDER BY", "WHERE", "SORT", 1],
    ["Which SQL clause filters groups?", "WHERE", "HAVING", "GROUP", "FILTER", 2],
    ["Which aggregate function calculates the total?", "COUNT()", "SUM()", "AVG()", "MAX()", 2],
    ["Which aggregate function calculates the average?", "SUM()", "AVG()", "COUNT()", "MIN()", 2],
    ["Which function returns the maximum value?", "MAX()", "MIN()", "HIGH()", "TOP()", 1],
    ["Which function returns the minimum value?", "MAX()", "MIN()", "LOW()", "BOTTOM()", 2],
    ["Which function counts rows?", "COUNT()", "NUMBER()", "TOTAL()", "ROWS()", 1],
    ["Which key uniquely identifies a record?", "Foreign Key", "Primary Key", "Composite Key", "Super Key", 2],
    ["Which key refers to a key in another table?", "Primary Key", "Foreign Key", "Candidate Key", "Super Key", 2],
    ["A key made of more than one attribute is called:", "Composite Key", "Foreign Key", "Simple Key", "Primary Value", 1],
    ["Which normal form eliminates repeating groups?", "1NF", "2NF", "3NF", "BCNF", 1],
    ["Which normal form eliminates partial dependency?", "1NF", "2NF", "3NF", "4NF", 2],
    ["Which normal form eliminates transitive dependency?", "1NF", "2NF", "3NF", "4NF", 3],
    ["What is normalization used for?", "Reducing data redundancy", "Increasing duplication", "Deleting databases", "Increasing file size", 1],
    ["What is a database transaction?", "A logical unit of work", "A table only", "A column only", "A password", 1],
    ["Which property of transactions means all-or-nothing?", "Consistency", "Atomicity", "Isolation", "Durability", 2],
    ["Which ACID property ensures committed data survives failures?", "Atomicity", "Consistency", "Isolation", "Durability", 4],
    ["Which ACID property ensures valid database state?", "Consistency", "Atomicity", "Isolation", "Durability", 1],
    ["Which ACID property separates concurrent transactions?", "Isolation", "Atomicity", "Consistency", "Durability", 1],
    ["What is a view in a database?", "A virtual table", "A physical disk", "A backup file", "A password", 1],
    ["What is the full form of OS?", "Operating System", "Open Software", "Operating Software", "Online System", 1],
    ["Which is an operating system?", "Linux", "MySQL", "Oracle", "Python", 1],
    ["Which operating system is open-source?", "Linux", "Windows only", "iOS only", "MS-DOS only", 1],
    ["What is a process?", "A program in execution", "A file only", "A folder", "A device", 1],
    ["What is a thread?", "Smallest unit of CPU execution within a process", "A hard disk", "A file", "A compiler", 1],
    ["Which state indicates that a process is currently executing?", "Ready", "Running", "Waiting", "Terminated", 2],
    ["Which state means a process is waiting for CPU?", "Ready", "Running", "Terminated", "New", 1],
    ["Which state means a process has finished execution?", "Ready", "Waiting", "Terminated", "Running", 3],
    ["Which scheduling algorithm serves processes in arrival order?", "FCFS", "SJF", "Round Robin", "Priority", 1],
    ["What is the full form of FCFS?", "First Come First Served", "First CPU First Served", "Fast Come Fast Served", "First Control First System", 1],
    ["Which scheduling algorithm uses a time quantum?", "FCFS", "SJF", "Round Robin", "FIFO", 3],
    ["Which scheduling algorithm selects the shortest CPU burst?", "FCFS", "SJF", "Round Robin", "FIFO", 2],
    ["What is starvation in operating systems?", "A process waits indefinitely", "CPU shuts down", "Memory increases", "A file is deleted", 1],
    ["Which technique can help prevent starvation?", "Aging", "Formatting", "Paging", "Spooling", 1],
    ["What is deadlock?", "Processes wait indefinitely for resources", "A process finishes", "CPU becomes faster", "Memory increases", 1],
    ["How many necessary conditions are there for deadlock?", "2", "3", "4", "5", 3],
    ["Which is a necessary condition for deadlock?", "Mutual Exclusion", "Compilation", "Paging", "Caching", 1],
    ["Which is NOT a necessary deadlock condition?", "Mutual Exclusion", "Hold and Wait", "Circular Wait", "Compilation", 4],
    ["What is virtual memory?", "Memory management technique using secondary storage", "CPU memory only", "Cache memory", "ROM", 1],
    ["What is paging?", "Memory management technique", "File compression", "CPU scheduling", "Encryption", 1],
    ["What is a page fault?", "Required page is not in main memory", "CPU failure", "Hard disk failure", "Network failure", 1],
    ["Which algorithm replaces the oldest page?", "FIFO", "LRU", "Optimal", "SJF", 1],
    ["Which page replacement algorithm replaces the least recently used page?", "FIFO", "LRU", "FCFS", "SJF", 2],
    ["What is thrashing?", "Excessive paging", "CPU scheduling", "Disk formatting", "File sharing", 1],
    ["Which memory is closest to CPU?", "Hard Disk", "Cache", "DVD", "USB", 2],
    ["What is fragmentation?", "Wasted memory space", "CPU scheduling", "Network failure", "Database backup", 1],
    ["External fragmentation occurs mainly in:", "Variable-size memory allocation", "CPU registers", "ROM", "Cache only", 1],
    ["Which allocation technique allocates memory in fixed-size blocks?", "Paging", "Segmentation", "Compaction", "Spooling", 1],
    ["Which system call creates a new process in Unix-like systems?", "fork()", "create()", "new()", "spawnfile()", 1],
    ["What is a shell?", "Command interpreter", "Hardware device", "Database", "Compiler only", 1],
    ["What is computer architecture?", "Design and organization of computer systems", "Programming language", "Database", "Network protocol", 1],
    ["Which unit performs arithmetic and logical operations?", "ALU", "CU", "RAM", "ROM", 1],
    ["Which unit directs computer operations?", "Control Unit", "ALU", "Register", "Cache", 1],
    ["Which register stores the address of the next instruction?", "Program Counter", "Accumulator", "IR", "MAR", 1],
    ["Which register stores the current instruction?", "IR", "PC", "MAR", "MDR", 1],
    ["What does MAR stand for?", "Memory Address Register", "Memory Access Register", "Main Address Register", "Machine Address Register", 1],
    ["What does MDR stand for?", "Memory Data Register", "Main Data Register", "Memory Device Register", "Machine Data Register", 1],
    ["Which register stores intermediate arithmetic results?", "Accumulator", "PC", "IR", "MAR", 1],
    ["What is the full form of CPU?", "Central Processing Unit", "Computer Processing Unit", "Central Program Unit", "Control Program Unit", 1],
    ["Which architecture uses separate memory for instructions and data?", "Harvard Architecture", "Von Neumann Architecture", "Pipeline Architecture", "Distributed Architecture", 1],
    ["Which architecture uses a common memory for instructions and data?", "Harvard", "Von Neumann", "RISC", "CISC", 2],
    ["What is RISC?", "Reduced Instruction Set Computer", "Rapid Instruction System Computer", "Random Instruction Set Computer", "Reduced Internal System Computer", 1],
    ["What is CISC?", "Complex Instruction Set Computer", "Central Instruction System Computer", "Computer Integrated System Computer", "Complex Internal System Computer", 1],
    ["Which architecture generally uses a smaller set of simple instructions?", "RISC", "CISC", "BIOS", "DMA", 1],
    ["What is pipelining?", "Overlapping instruction execution stages", "Memory deletion", "Disk formatting", "Network routing", 1],
    ["What is cache memory used for?", "Reducing memory access time", "Permanent storage", "Printing", "Networking", 1],
    ["Which cache is usually fastest?", "L1", "L2", "L3", "Hard Disk", 1],
    ["What is clock speed measured in?", "Hertz", "Bytes", "Pixels", "Volts only", 1],
    ["A CPU speed of 3 GHz means approximately:", "3 billion cycles per second", "3 million bytes", "3 thousand instructions", "3 bytes per second", 1],
    ["What is DMA?", "Direct Memory Access", "Data Memory Allocation", "Direct Machine Access", "Dynamic Memory Access", 1],
    ["DMA allows devices to transfer data directly to:", "Memory", "Printer only", "CPU register only", "Monitor", 1],
    ["What is an interrupt?", "Signal requesting CPU attention", "A database", "A programming language", "A file", 1],
    ["What is BIOS?", "Basic Input/Output System", "Binary Input Output Software", "Basic Internal Operating System", "Boot Input Operating Service", 1],
    ["Where is firmware commonly stored?", "ROM/Flash Memory", "RAM only", "Cache only", "Register only", 1],
    ["What is booting?", "Starting the computer and loading the OS", "Deleting files", "Installing RAM", "Formatting CPU", 1],
    ["What is an algorithm?", "A step-by-step procedure to solve a problem", "A programming language", "A database", "A computer virus", 1],
    ["Which notation is commonly used to represent algorithm complexity?", "Big-O", "HTML", "SQL", "ASCII", 1],
    ["What is the time complexity of accessing an array element by index?", "O(1)", "O(n)", "O(log n)", "O(n²)", 1],
    ["What is the worst-case time complexity of linear search?", "O(1)", "O(log n)", "O(n)", "O(n²)", 3],
    ["What is the best-case time complexity of linear search?", "O(1)", "O(n)", "O(log n)", "O(n²)", 1],
    ["What is the worst-case complexity of binary search?", "O(n)", "O(log n)", "O(n²)", "O(1)", 2],
    ["Which sorting algorithm has O(n log n) worst-case complexity?", "Merge Sort", "Bubble Sort", "Selection Sort", "Linear Search", 1],
    ["Which sorting algorithm can have O(n²) worst-case complexity?", "Quick Sort", "Merge Sort", "Heap Sort", "Counting Sort", 1],
    ["Which algorithm is used to find a minimum spanning tree?", "Kruskal's Algorithm", "Binary Search", "DFS only", "Linear Search", 1],
    ["Which algorithm is another minimum spanning tree algorithm?", "Prim's Algorithm", "Dijkstra's only", "BFS only", "Merge Sort", 1],
    ["Which algorithm is used for all-pairs shortest paths?", "Floyd-Warshall", "Binary Search", "Kruskal", "DFS", 1],
    ["Which algorithm uses a greedy approach for shortest paths with non-negative edges?", "Dijkstra", "Merge Sort", "DFS", "Binary Search", 1],
    ["Which algorithm can handle negative edge weights?", "Bellman-Ford", "Binary Search", "Prim", "Heap Sort", 1],
    ["What is recursion?", "A function calling itself", "A loop only", "A database query", "A network protocol", 1],
    ["What must a recursive function generally have?", "Base case", "Database", "Compiler", "Pointer only", 1],
    ["What is dynamic programming?", "Solving overlapping subproblems and storing results", "Dynamic memory only", "CPU scheduling", "Network routing", 1],
    ["Which approach divides a problem into smaller independent parts?", "Divide and Conquer", "Deadlock", "Paging", "Hashing", 1],
    ["Which algorithm is a classic divide-and-conquer algorithm?", "Merge Sort", "Bubble Sort", "Linear Search", "Counting", 1],
    ["What is greedy algorithm?", "Makes the locally best choice at each step", "Always uses recursion", "Uses only sorting", "Uses databases", 1],
    ["Which is a greedy algorithm?", "Kruskal's Algorithm", "Merge Sort", "Binary Search", "Floyd-Warshall", 1],
    ["What is backtracking?", "Trying choices and undoing invalid choices", "Sorting data", "Deleting memory", "Routing packets", 1],
    ["Which problem commonly uses backtracking?", "N-Queens", "Binary Search", "Bubble Sort", "DNS", 1],
    ["What is the space complexity of an array of n elements?", "O(1)", "O(n)", "O(log n)", "O(n²)", 2],
    ["Which data structure is suitable for implementing undo operations?", "Stack", "Queue", "Graph", "Heap", 1],
    ["Which data structure is suitable for task scheduling in arrival order?", "Queue", "Stack", "Tree", "Graph", 1],
    ["Which keyword is used to define a class in C++?", "class", "structclass", "object", "define", 1],
    ["Which keyword creates an object dynamically in C++?", "new", "malloconly", "object", "create", 1],
    ["Which concept hides internal implementation details?", "Abstraction", "Inheritance", "Overloading", "Compilation", 1],
    ["Which concept combines data and methods?", "Encapsulation", "Inheritance", "Recursion", "Compilation", 1],
    ["Which concept allows deriving a new class from an existing class?", "Inheritance", "Abstraction", "Encapsulation", "Overloading", 1],
    ["Which concept allows one interface to have multiple implementations?", "Polymorphism", "Inheritance", "Compilation", "Debugging", 1],
    ["Which access specifier makes members accessible only within the class?", "private", "public", "protected", "global", 1],
    ["Which access specifier allows access from anywhere through the object?", "private", "public", "protected", "local", 2],
    ["Which access specifier allows class and derived class access?", "private", "public", "protected", "static", 3],
    ["What is a constructor?", "Special member function used to initialize objects", "Destructor", "Variable", "Header file", 1],
    ["What is a destructor used for?", "Object cleanup", "Object creation", "Compilation", "Inheritance", 1],
    ["What is the name of a constructor in C++?", "Same as class name", "main", "constructor", "new", 1],
    ["Which symbol is used before a destructor name?", "~", "#", "@", "$", 1],
    ["Can constructors have a return type?", "Yes", "No", "Only int", "Only void", 2],
    ["Which function is automatically called when an object is created?", "Constructor", "Destructor", "main", "friend", 1],
    ["Which function is automatically called when an object is destroyed?", "Constructor", "Destructor", "main", "virtual", 2],
    ["What is function overloading?", "Same function name with different parameters", "Different names with same parameters", "Inheritance", "Encapsulation", 1],
    ["What is operator overloading?", "Giving operators new meaning for user-defined types", "Creating new operators", "Deleting operators", "Changing CPU operators", 1],
    ["What is method overriding?", "Derived class provides its own implementation of a base method", "Creating variables", "Function overloading only", "Compilation", 1],
    ["Which keyword supports runtime polymorphism in C++?", "virtual", "static", "friend", "const", 1],
    ["What is a virtual function?", "A function that can be overridden in a derived class", "A private variable", "A constructor", "A static function only", 1],
    ["What is an abstract class?", "A class that cannot normally be instantiated", "A class with no methods", "A class with only variables", "A private class", 1],
    ["Which keyword can declare a pure virtual function?", "virtual", "pure", "abstract", "interface", 1],
    ["What is a friend function?", "A non-member function allowed access to private/protected members", "A constructor", "A derived class", "A virtual class", 1],
    ["Which keyword is used to prevent modification of a variable?", "const", "static", "private", "final", 1],
    ["What is inheritance where one class inherits from one base class?", "Single inheritance", "Multiple inheritance", "Multilevel inheritance", "Hybrid inheritance", 1],
    ["What is inheritance where a class has more than one base class?", "Single", "Multiple", "Multilevel", "Hierarchical", 2],
    ["What is inheritance where a derived class becomes a base for another class?", "Multilevel", "Single", "Multiple", "Hybrid", 1],
    ["Which language is primarily object-oriented?", "Java", "Assembly", "Machine Code", "Binary", 1],
    ["What is JVM?", "Java Virtual Machine", "Java Variable Machine", "Java Visual Model", "Java Virtual Memory", 1],
    ["What is JDK?", "Java Development Kit", "Java Design Kit", "Java Debug Kit", "Java Data Kit", 1],
    ["What is JRE?", "Java Runtime Environment", "Java Resource Environment", "Java Runtime Engine", "Java Research Environment", 1],
    ["Which keyword is used to inherit a class in Java?", "extends", "inherits", "implements", "super", 1],
    ["Which keyword is used to implement an interface in Java?", "implements", "extends", "interface", "inherits", 1],
    ["Which language is known for 'Write Once, Run Anywhere'?", "Java", "C", "Assembly", "SQL", 1],
    ["Which of the following is not a primitive data type in Java?", "int", "char", "boolean", "String", 4],
    ["Which keyword creates an object in Java?", "new", "create", "object", "make", 1],
    ["Which Java method is the entry point of a program?", "main()", "start()", "run()", "init()", 1],
    ["Which language is dynamically typed?", "Python", "C", "C++", "Java", 1],
    ["Who created Python?", "Guido van Rossum", "Dennis Ritchie", "Bjarne Stroustrup", "James Gosling", 1],
    ["Which symbol is used to create a comment in Python?", "#", "//", "/*", "<!--", 1],
    ["Which function is used to display output in Python?", "print()", "display()", "output()", "show()", 1],
    ["Which function takes input from the user in Python?", "input()", "scan()", "read()", "get()", 1],
    ["Which data type stores True or False?", "bool", "int", "str", "float", 1],
    ["Which Python data type is immutable?", "tuple", "list", "set", "dictionary", 1],
    ["Which Python data type is mutable?", "list", "tuple", "string", "int", 1],
    ["Which symbol is used to create a list in Python?", "[]", "{}", "()", "<>", 1],
    ["Which symbol is used to create a tuple?", "[]", "()", "{}", "<>", 2],
    ["Which data structure stores key-value pairs in Python?", "List", "Tuple", "Dictionary", "Set", 3],
    ["Which keyword defines a function in Python?", "def", "function", "func", "define", 1],
    ["What is the full form of AI?", "Artificial Intelligence", "Automated Information", "Artificial Information", "Advanced Intelligence", 1],
    ["What is Machine Learning?", "A subset of AI that learns from data", "A database", "A network protocol", "An operating system", 1],
    ["Which is a supervised learning algorithm?", "Linear Regression", "K-Means", "PCA", "Apriori", 1],
    ["Which is an unsupervised learning algorithm?", "K-Means", "Linear Regression", "Logistic Regression", "Decision Tree with labels", 1],
    ["Which learning uses labeled data?", "Supervised Learning", "Unsupervised Learning", "Reinforcement Learning", "Random Learning", 1],
    ["Which learning uses rewards and penalties?", "Supervised", "Unsupervised", "Reinforcement Learning", "Batch Learning", 3],
    ["What is classification?", "Predicting categories/classes", "Predicting only continuous values", "Clustering only", "Sorting files", 1],
    ["What is regression?", "Predicting continuous values", "Predicting categories only", "Clustering", "Encryption", 1],
    ["Which algorithm is commonly used for classification?", "Logistic Regression", "Linear Regression only", "K-Means only", "PCA", 1],
    ["Which algorithm is used for clustering?", "K-Means", "Linear Regression", "Logistic Regression", "Naive Bayes", 1],
    ["What is overfitting?", "Model performs well on training data but poorly on unseen data", "Model is too simple", "Data is missing", "CPU is slow", 1],
    ["What is underfitting?", "Model is too simple to capture patterns", "Model memorizes training data", "Model has too many features", "Database failure", 1],
    ["What is a feature in machine learning?", "Input variable", "Output only", "Algorithm only", "Database table", 1],
    ["What is a label in supervised learning?", "Target output", "Input feature", "Model", "Optimizer", 1],
    ["What is training data?", "Data used to train a model", "Only test data", "Deleted data", "Encrypted data", 1],
    ["What is test data used for?", "Evaluating model performance", "Training only", "Deleting features", "Creating hardware", 1],
    ["What is accuracy?", "Correct predictions divided by total predictions", "False positives only", "Loss only", "Training time", 1],
    ["What is precision?", "True Positives / (True Positives + False Positives)", "TP / All actual positives", "TN / All negatives", "FP / TP", 1],
    ["What is recall?", "True Positives / (True Positives + False Negatives)", "TP / FP", "TN / TP", "FP / FN", 1],
    ["What is F1-score?", "Harmonic mean of precision and recall", "Average accuracy", "Training loss", "Model size", 1],
    ["What is a neural network inspired by?", "Human brain", "Database", "Router", "Compiler", 1],
    ["What is an artificial neuron?", "Basic computational unit of a neural network", "A CPU", "A database row", "A network cable", 1],
    ["Which activation function outputs values between 0 and 1?", "Sigmoid", "ReLU", "Linear", "Step only", 1],
    ["Which activation function is max(0,x)?", "ReLU", "Sigmoid", "Tanh", "Softmax", 1],
    ["Which activation function is commonly used for multi-class output probabilities?", "Softmax", "ReLU", "Linear", "Step", 1],
    ["What is backpropagation?", "Algorithm for computing gradients in neural networks", "Data storage", "Database backup", "Network routing", 1],
    ["What is an epoch in machine learning?", "One complete pass through training data", "One feature", "One neuron", "One prediction", 1],
    ["What is a batch?", "Subset of training examples processed together", "A model", "A feature", "A label", 1],
    ["What is a learning rate?", "Step size used during optimization", "Dataset size", "Number of classes", "Model accuracy", 1],
    ["Which algorithm is commonly used to optimize neural networks?", "Gradient Descent", "Binary Search", "DFS", "BFS", 1],
    ["What is NLP?", "Natural Language Processing", "Network Language Protocol", "Natural Learning Program", "Neural Logic Processing", 1],
    ["What is tokenization in NLP?", "Splitting text into tokens", "Encrypting text", "Deleting text", "Translating hardware", 1],
    ["What is an embedding?", "Numerical vector representation of data", "A database", "A compiler", "A network cable", 1],
    ["What does LLM stand for?", "Large Language Model", "Long Learning Machine", "Language Logic Model", "Large Logic Machine", 1],
    ["What architecture is widely used by modern LLMs?", "Transformer", "Linked List", "Von Neumann only", "Ring", 1],
    ["What mechanism is central to the Transformer architecture?", "Self-Attention", "Binary Search", "Paging", "Hashing", 1],
    ["What is an AI model trained on?", "Data", "Only hardware", "Only electricity", "Only networks", 1],
    ["What is a prompt?", "Input/instruction given to an AI model", "Output only", "Database", "CPU instruction only", 1],
    ["What is computer vision?", "AI field dealing with images and visual data", "Database management", "Network routing", "Operating systems", 1],
    ["Which task is an example of computer vision?", "Image classification", "SQL query", "CPU scheduling", "File compression", 1],
    ["What is software engineering?", "Systematic development and maintenance of software", "Hardware manufacturing", "Network cabling", "Database only", 1],
    ["What is SDLC?", "Software Development Life Cycle", "System Data Logic Control", "Software Design Language Code", "System Development Logic Cycle", 1],
    ["Which is a phase of SDLC?", "Requirements Analysis", "Only Coding", "Only Testing", "Only Deployment", 1],
    ["What happens during requirements analysis?", "Understanding system requirements", "Writing only code", "Deleting software", "Buying hardware", 1],
    ["Which SDLC model follows sequential phases?", "Waterfall", "Agile", "Spiral only", "Prototype only", 1],
    ["Which methodology emphasizes iterative development?", "Agile", "Waterfall", "Big Bang only", "Assembly", 1],
    ["What is debugging?", "Finding and fixing program errors", "Writing requirements", "Designing hardware", "Installing OS", 1],
    ["What is software testing?", "Evaluating software to find defects", "Writing hardware", "Compiling only", "Formatting disks", 1],
    ["Testing individual modules is called:", "Unit Testing", "System Testing", "Acceptance Testing", "Integration Testing", 1],
    ["Testing combined modules is called:", "Integration Testing", "Unit Testing", "Alpha Testing", "Stress Testing", 1]
];

export default questions;

